package:
   name: minuit2
   version: "5.34.14"

source:
  url: http://www.cern.ch/mathlibs/sw/5_34_14/Minuit2/Minuit2-5.34.14.tar.gz


build:
  number: 1
  string: lsstdm_1

requirements:
   build:
      - libtool
      - {{ compiler('cxx') }}
